import { motion } from "framer-motion";
import { CheckCircle2, CircleAlert, Crosshair, Flag, GitBranch, RotateCcw, Target } from "lucide-react";
import { useIncidentStore } from "@/application/incident/incidentStore";
import { Panel, PrimaryButton, SeverityText } from "../shared/ui";

function clockLabel(minute: number, startMinute: number) { const total = startMinute + minute; return `${String(Math.floor(total / 60)).padStart(2, "0")}:${String(total % 60).padStart(2, "0")}`; }
function scoreLabel(score: number) { return score >= 90 ? "Incident Commander" : score >= 70 ? "Strong Response" : score >= 50 ? "Partial Containment" : "Failure Chain Unbroken"; }

export function AutopsyReport() {
  const incident = useIncidentStore((state) => state.incident);
  const scenario = useIncidentStore((state) => state.scenario);
  const restart = useIncidentStore((state) => state.restart);
  const outcome = incident.outcome ?? "major-outage";
  const copy = scenario.content.outcomeMessages[outcome] ?? { eyebrow: "Incident complete", title: "The investigation is complete.", body: "Review the decisions and signals that shaped the outcome.", tone: "text-slate-300" };
  const score = scenario.calculateScore(incident);
  const label = scoreLabel(score);
  const missed = scenario.content.report.missedOpportunities.filter(({ flag }) => !incident.flags[flag]).map(({ label }) => label);
  const report = scenario.content.report;

  return <main className="min-h-screen bg-[#080b10] px-5 py-8 text-slate-100 sm:px-8 lg:px-12"><div className="mx-auto max-w-6xl">
    <header className="flex items-center justify-between border-b border-white/[0.08] pb-6"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl border border-cyan-300/30 bg-cyan-300/10 text-cyan-200"><Crosshair size={18} /></div><span className="text-sm font-bold tracking-[0.16em]">INCIDENT AUTOPSY</span></div><span className="text-[10px] font-bold uppercase tracking-[0.2em] text-slate-500">{scenario.title} / final report</span></header>
    <div className="grid gap-6 pb-16 pt-10 lg:grid-cols-[1.1fr_0.9fr]"><motion.section initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}><p className={`text-[10px] font-bold uppercase tracking-[0.22em] ${copy.tone}`}>{copy.eyebrow}</p><h1 className="mt-3 max-w-2xl text-4xl font-semibold leading-tight tracking-[-0.045em] sm:text-6xl">{copy.title}</h1><p className="mt-5 max-w-xl text-base leading-7 text-slate-400">{copy.body}</p><div className="mt-8 flex flex-wrap gap-3"><PrimaryButton onClick={restart} className="gap-2"><RotateCcw size={16} /> Replay incident</PrimaryButton><span className="inline-flex items-center gap-2 rounded-xl border border-white/[0.08] px-4 py-3 text-sm text-slate-400"><Flag size={15} className="text-cyan-200" /> {label}</span></div></motion.section><Panel className="p-6"><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-slate-500">Response score</p><p className="mt-2 text-6xl font-semibold tracking-[-0.06em] text-white">{score}<span className="ml-1 text-xl text-slate-600">/100</span></p><div className="mt-6 h-2 overflow-hidden rounded-full bg-white/[0.07]"><div className="h-full rounded-full bg-cyan-300" style={{ width: `${score}%` }} /></div><p className="mt-4 text-xs leading-5 text-slate-500">The score is secondary. The decision review below is where the learning is.</p></Panel></div>
    <div className="grid gap-5 border-t border-white/[0.08] pt-8 lg:grid-cols-2"><Panel className="p-6"><div className="mb-5 flex items-center gap-3"><GitBranch size={18} className="text-red-300" /><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-slate-500">Root cause</p><h2 className="font-semibold text-slate-100">{report.rootCauseTitle}</h2></div></div><p className="text-sm leading-6 text-slate-400">{report.rootCauseDescription}</p><div className="mt-5 rounded-xl border border-white/[0.07] bg-white/[0.02] p-3"><p className="text-[10px] uppercase tracking-[0.14em] text-slate-600">Best intervention</p><p className="mt-1 text-sm font-semibold text-cyan-100">{report.bestIntervention}</p></div></Panel><Panel className="p-6"><div className="mb-5 flex items-center gap-3"><Target size={18} className="text-amber-200" /><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-slate-500">Missed opportunities</p><h2 className="font-semibold text-slate-100">What could change next time</h2></div></div>{missed.length ? <ul className="space-y-3">{missed.map((item) => <li key={item} className="flex items-center gap-3 text-sm text-slate-400"><CircleAlert size={15} className="text-amber-200" />{item}</li>)}</ul> : <p className="flex items-center gap-2 text-sm text-emerald-300"><CheckCircle2 size={16} /> No major intervention was missed.</p>}</Panel>
      <Panel className="p-6 lg:col-span-2"><div className="mb-5 flex items-center gap-3"><GitBranch size={18} className="text-cyan-200" /><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-slate-500">Decision review</p><h2 className="font-semibold text-slate-100">Your investigation timeline</h2></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{incident.timeline.map((event) => <div key={event.id} className="rounded-xl border border-white/[0.07] bg-white/[0.02] p-4"><div className="flex items-center justify-between"><span className="font-mono text-xs text-cyan-200">{clockLabel(event.minute, scenario.content.startMinute)}</span><SeverityText severity={event.severity} /></div><p className="mt-2 text-sm font-semibold text-slate-200">{event.title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{event.description}</p></div>)}</div></Panel>
      <Panel className="p-6 lg:col-span-2"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-slate-500">Concepts learned</p><div className="mt-4 flex flex-wrap gap-2">{scenario.concepts.map((concept) => <span key={concept} className="rounded-full border border-cyan-300/15 bg-cyan-300/[0.05] px-3 py-2 text-xs text-cyan-100">{concept}</span>)}</div></Panel>
    </div>
  </div></main>;
}
