import type { IncidentAction, IncidentEvent, Metric, NodeStatus, SystemNode } from "@/domain/incident/types";
export const metricIds = { heapUsed: "heapUsed", heapGrowthRate: "heapGrowthRate", gcPause: "gcPause", requestRate: "requestRate", restartCount: "restartCount", lostWork: "lostWork", errorRate: "errorRate" } as const;
export const nodeIds = { webCheckout: "web-checkout", checkoutApi: "checkout-api", workerPool: "worker-pool", heap: "heap", cache: "cache", database: "database", telemetry: "telemetry" } as const;
const metric = (id: string, label: string, value: number, unit: string, severity: Metric["severity"], explanation: string): Metric => ({ id, label, value, unit, trend: "flat", severity, explanation });
export const initialMetrics: Record<string, Metric> = {
  [metricIds.heapUsed]: metric(metricIds.heapUsed, "Heap used", 68, "%", "warning", "Heap usage is high, but CPU and request volume remain normal."),
  [metricIds.heapGrowthRate]: metric(metricIds.heapGrowthRate, "Post-GC heap growth", 2.4, "%/min", "warning", "The heap baseline continues to rise after garbage collection."),
  [metricIds.gcPause]: metric(metricIds.gcPause, "GC pause p95", 180, "ms", "warning", "Garbage collection is beginning to affect worker responsiveness."),
  [metricIds.requestRate]: metric(metricIds.requestRate, "Checkout request rate", 820, "/min", "info", "Traffic is normal for this time of day."),
  [metricIds.restartCount]: metric(metricIds.restartCount, "Worker restarts", 0, "restarts", "info", "No workers have restarted yet."),
  [metricIds.lostWork]: metric(metricIds.lostWork, "Lost in-flight work", 0, "requests", "info", "No customer work has been lost yet."),
  [metricIds.errorRate]: metric(metricIds.errorRate, "Checkout error rate", 1.4, "%", "info", "Customer errors are low while memory pressure is still building."),
};
export const nodes: Record<string, SystemNode> = { [nodeIds.webCheckout]: { id: nodeIds.webCheckout, name: "Web Checkout", description: "Customer-facing checkout flow." }, [nodeIds.checkoutApi]: { id: nodeIds.checkoutApi, name: "Checkout API", description: "Routes work to application workers." }, [nodeIds.workerPool]: { id: nodeIds.workerPool, name: "Worker Pool", description: "Processes requests and owns the leaking objects." }, [nodeIds.heap]: { id: nodeIds.heap, name: "Application Heap", description: "Managed memory reclaimed by garbage collection." }, [nodeIds.cache]: { id: nodeIds.cache, name: "Session Cache", description: "A cache retaining objects longer than intended." }, [nodeIds.database]: { id: nodeIds.database, name: "Database", description: "Healthy persistence downstream." }, [nodeIds.telemetry]: { id: nodeIds.telemetry, name: "Telemetry", description: "Collects runtime and GC diagnostics." } };
export const connections = [{ from: nodeIds.webCheckout, to: nodeIds.checkoutApi }, { from: nodeIds.checkoutApi, to: nodeIds.workerPool }, { from: nodeIds.workerPool, to: nodeIds.heap }, { from: nodeIds.heap, to: nodeIds.cache }, { from: nodeIds.checkoutApi, to: nodeIds.database }, { from: nodeIds.workerPool, to: nodeIds.telemetry }];
export const actions: IncidentAction[] = [
  { id: "inspect-memory-metrics", title: "Inspect memory metrics", description: "Compare heap usage before and after garbage collection.", consequence: "Post-GC heap keeps rising instead of returning to a stable baseline.", actionPointCost: 1, timeCostMinutes: 1 },
  { id: "inspect-heap-profile", title: "Inspect heap profile", description: "Find object types retained between garbage collections.", consequence: "A session cache retains request objects beyond their intended lifetime.", actionPointCost: 1, timeCostMinutes: 2, prerequisites: ["inspect-memory-metrics"] },
  { id: "limit-cache", title: "Limit cache growth", description: "Cap the leaking cache and evict retained request objects.", consequence: "Heap growth slows and workers begin to recover after the next collection.", actionPointCost: 1, timeCostMinutes: 2, prerequisites: ["inspect-memory-metrics"], prerequisiteMode: "any" },
  { id: "restart-workers", title: "Restart workers", description: "Reclaim heap immediately by recycling application workers.", consequence: "Memory drops, but in-flight requests are interrupted and the leak remains.", actionPointCost: 1, timeCostMinutes: 2 },
  { id: "shed-traffic", title: "Shed checkout traffic", description: "Reduce incoming work while memory pressure is critical.", consequence: "Workers gain headroom at a direct customer availability cost.", actionPointCost: 2, timeCostMinutes: 1 },
  { id: "increase-memory", title: "Increase worker memory", description: "Raise the memory limit to buy more time.", consequence: "The failure threshold moves out, but retained objects continue to accumulate.", actionPointCost: 1, timeCostMinutes: 1 },
  { id: "advance-time", title: "Advance incident timeline", description: "Wait and observe whether the current mitigation holds.", consequence: "The heap continues to grow while the leak is active.", actionPointCost: 1, timeCostMinutes: 2 },
];
export const initialStatuses: Record<string, NodeStatus> = { [nodeIds.webCheckout]: "healthy", [nodeIds.checkoutApi]: "warning", [nodeIds.workerPool]: "warning", [nodeIds.heap]: "critical", [nodeIds.cache]: "warning", [nodeIds.database]: "healthy", [nodeIds.telemetry]: "warning" };
export const initialEvent: IncidentEvent = { id: "memory-leak-started", minute: 0, title: "Post-GC heap baseline rises", description: "Normal checkout traffic continues, but memory does not return to its previous baseline after collection.", severity: "warning", relatedNodeIds: [nodeIds.heap, nodeIds.workerPool] };
