import { useMemo } from "react";
import { AlertCircle, Check, X } from "lucide-react";
import { useIncidentStore } from "@/application/incident/incidentStore";
import { ActionCard } from "./ActionCard";
import { Panel, PrimaryButton, SectionHeading, SecondaryButton } from "../shared/ui";

export function ActionPanel() {
  const incident = useIncidentStore((state) => state.incident);
  const scenario = useIncidentStore((state) => state.scenario);
  const pendingActionId = useIncidentStore((state) => state.pendingActionId);
  const requestAction = useIncidentStore((state) => state.requestAction);
  const confirmAction = useIncidentStore((state) => state.confirmAction);
  const cancelAction = useIncidentStore((state) => state.cancelAction);
  const pendingAction = scenario.actions.find((action) => action.id === pendingActionId);
  const isAvailable = useMemo(() => (actionId: string) => { const action = scenario.actions.find((candidate) => candidate.id === actionId); if (!action) return false; if (incident.completedActionIds.includes(action.id)) return false; if (incident.actionPoints < action.actionPointCost) return false; const prerequisites = action.prerequisites ?? []; return action.prerequisiteMode === "any" ? prerequisites.some((id) => incident.completedActionIds.includes(id)) : prerequisites.every((id) => incident.completedActionIds.includes(id)); }, [incident, scenario]);
  return <><Panel className="p-5"><SectionHeading eyebrow="Limited budget" title="Available actions" action={<span className="text-xs text-cyan-200">{incident.actionPoints} points</span>} /><div className="space-y-2">{scenario.actions.map((action) => <ActionCard key={action.id} action={action} available={isAvailable(action.id)} completed={incident.completedActionIds.includes(action.id)} onSelect={() => requestAction(action.id)} />)}</div></Panel>{pendingAction && <div className="fixed inset-0 z-40 grid place-items-center bg-black/70 p-5 backdrop-blur-sm"><div className="w-full max-w-md rounded-2xl border border-white/10 bg-[#111720] p-6 shadow-2xl" role="dialog" aria-modal="true" aria-labelledby="action-confirm-title"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-cyan-200">Confirm intervention</p><h2 id="action-confirm-title" className="mt-2 text-xl font-semibold text-slate-100">{pendingAction.title}?</h2></div><button type="button" onClick={cancelAction} aria-label="Close confirmation" className="rounded-lg p-1.5 text-slate-500 hover:bg-white/5 hover:text-slate-200"><X size={18} /></button></div><p className="mt-4 text-sm leading-6 text-slate-400">This uses <strong className="text-slate-200">{pendingAction.actionPointCost} action point{pendingAction.actionPointCost > 1 ? "s" : ""}</strong> and advances the clock by <strong className="text-slate-200">{pendingAction.timeCostMinutes} minutes</strong>. The exact consequence will be revealed after you commit.</p><div className="mt-6 flex justify-end gap-3"><SecondaryButton onClick={cancelAction}>Cancel</SecondaryButton><PrimaryButton onClick={confirmAction} className="gap-2">Commit action <Check size={15} /></PrimaryButton></div></div></div>}{!pendingAction && incident.actionPoints === 0 && incident.status === "active" && <div className="mt-3 flex gap-2 rounded-xl border border-amber-300/20 bg-amber-300/[0.06] p-3 text-xs leading-5 text-amber-100"><AlertCircle size={15} className="mt-0.5 shrink-0" />No action points remain. The next signal will decide the incident.</div>}</>;
}
