import type { ScenarioCatalogEntry } from "./types";

export const scenarioCatalog: ScenarioCatalogEntry[] = [
  {
    id: "retry-storm",
    title: "Retry Storm",
    order: 1,
    difficulty: "Beginner",
    status: "available",
    summary: "A downstream timeout becomes an amplification loop through aggressive retries.",
    estimatedMinutes: 8,
    prerequisites: [],
    concepts: ["timeouts", "retry amplification", "circuit breakers", "blast radius"],
  },
  {
    id: "cache-stampede",
    title: "Cache Stampede",
    order: 2,
    difficulty: "Beginner",
    status: "available",
    summary: "A popular cache key expires and a wave of requests hits the database at once.",
    estimatedMinutes: 8,
    prerequisites: ["retry-storm"],
    concepts: ["TTL", "cache warming", "request coalescing", "database load"],
  },
  {
    id: "queue-consumer-lag",
    title: "Queue Consumer Lag",
    order: 3,
    difficulty: "Beginner",
    status: "available",
    summary: "Message arrival outpaces consumers and operational delay quietly compounds.",
    estimatedMinutes: 9,
    prerequisites: ["retry-storm"],
    concepts: ["throughput", "backpressure", "consumer lag", "autoscaling"],
  },
  {
    id: "connection-pool-exhaustion",
    title: "Connection Pool Exhaustion",
    order: 4,
    difficulty: "Intermediate",
    status: "available",
    summary: "Slow queries and unreleased connections starve otherwise healthy application workers.",
    estimatedMinutes: 10,
    prerequisites: ["queue-consumer-lag"],
    concepts: ["connection pools", "timeouts", "resource leaks", "query latency"],
  },
  {
    id: "memory-leak",
    title: "Memory Leak",
    order: 5,
    difficulty: "Intermediate",
    status: "available",
    summary: "A gradual heap growth pattern turns normal traffic into repeated restarts and lost work.",
    estimatedMinutes: 10,
    prerequisites: ["bad-deployment"],
    concepts: ["heap", "garbage collection", "profiling", "restart strategy"],
  },
  {
    id: "bad-deployment",
    title: "Bad Deployment",
    order: 6,
    difficulty: "Intermediate",
    status: "available",
    summary: "A release introduces failures for only part of the traffic, making rollback ambiguous.",
    estimatedMinutes: 11,
    prerequisites: ["connection-pool-exhaustion"],
    concepts: ["canary release", "rollback", "feature flags", "blast radius"],
  },
  {
    id: "database-lock-storm",
    title: "Database Lock Storm",
    order: 7,
    difficulty: "Advanced",
    status: "planned",
    summary: "Concurrent transactions block critical work until throughput collapses behind lock waits.",
    estimatedMinutes: 12,
    prerequisites: ["connection-pool-exhaustion", "bad-deployment"],
    concepts: ["locks", "deadlocks", "isolation levels", "transaction ordering"],
  },
  {
    id: "hot-partition",
    title: "Hot Partition",
    order: 8,
    difficulty: "Advanced",
    status: "planned",
    summary: "One tenant or key concentrates traffic on a single partition while aggregate metrics look fine.",
    estimatedMinutes: 12,
    prerequisites: ["queue-consumer-lag", "bad-deployment"],
    concepts: ["sharding", "partition skew", "noisy neighbor", "load distribution"],
  },
  {
    id: "cascading-failure",
    title: "Cascading Failure",
    order: 9,
    difficulty: "Advanced",
    status: "planned",
    summary: "A degraded dependency spreads timeout pressure and retries across several services.",
    estimatedMinutes: 14,
    prerequisites: ["retry-storm", "connection-pool-exhaustion", "bad-deployment"],
    concepts: ["bulkheads", "timeout budgets", "dependency graphs", "graceful degradation"],
  },
  {
    id: "distributed-incident",
    title: "Distributed Incident",
    order: 10,
    difficulty: "Advanced",
    status: "planned",
    summary: "Several plausible causes compete for attention while the blast radius changes in real time.",
    estimatedMinutes: 16,
    prerequisites: ["retry-storm", "cascading-failure"],
    concepts: ["correlation", "hypotheses", "uncertainty", "incident command"],
  },
];
